version: "3.3"
services:
    app-backend:
        build: ./SuperAPI/
        image: barsheffer/backv1
        container_name: backend
        restart: always
        ports:
            - "12580:12580"
    app-frontend:
        build: ./src\Frontend/
        image: barsheffer/frontv1
        container_name: frontend
        restart: always
        ports:
            - "4200:4200"
        links:
            - app-backend   