# Generated by Django 3.2 on 2022-04-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseHandler', '0002_casetag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseTag',
        ),
    ]
