# Generated by Django 3.2 on 2022-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('reference_type', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=100)),
                ('investigating_unit', models.CharField(max_length=100)),
                ('internal_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('internal_number_year', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=100)),
                ('received_date', models.CharField(max_length=100)),
                ('sign_date', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.CharField(max_length=32)),
                ('exhibit_number', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('amount', models.CharField(max_length=32)),
                ('destination', models.CharField(max_length=128)),
                ('explosive', models.CharField(max_length=32)),
                ('explosive_weight', models.CharField(max_length=32)),
                ('tnt_equivalent', models.CharField(max_length=32)),
                ('received_date', models.CharField(max_length=32)),
                ('handle_date', models.CharField(max_length=32)),
                ('investigator_name', models.CharField(max_length=128)),
                ('lab_name', models.CharField(max_length=128)),
                ('result', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('internal_number', 'exhibit_number')},
            },
        ),
    ]
