# Generated by Django 3.2 on 2022-04-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseHandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTag',
            fields=[
                ('internal_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('weapon_name', models.CharField(max_length=256)),
                ('explosive_device_material', models.CharField(max_length=256)),
                ('explosive_device_means', models.CharField(max_length=256)),
                ('weapon_options', models.CharField(max_length=256)),
                ('explosive_device_operating_system', models.CharField(max_length=256)),
                ('weapon_mark', models.CharField(max_length=256)),
                ('explosive_device_spray', models.CharField(max_length=256)),
                ('weapon_color', models.CharField(max_length=256)),
                ('explosive_device_camouflage', models.CharField(max_length=256)),
                ('weapon_additional_characteristics', models.CharField(max_length=256)),
            ],
        ),
    ]
