# Generated by Django 3.2 on 2022-05-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseHandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=32)),
                ('exhibit_id', models.CharField(max_length=32)),
                ('sample_id', models.CharField(max_length=32)),
                ('what_sampled', models.CharField(max_length=256)),
                ('where_sampled', models.CharField(max_length=256)),
                ('transferred_to_lab', models.CharField(choices=[('S', 'דרום'), ('TLV', 'תל אביב'), ('N', 'צפון'), ('MATAR', 'מטא"ר')], max_length=5)),
                ('sending_date', models.CharField(max_length=16)),
                ('receiving_date', models.CharField(max_length=16)),
                ('packaging', models.CharField(max_length=64)),
                ('results', models.CharField(max_length=512)),
                ('notes', models.CharField(max_length=512)),
                ('date', models.CharField(max_length=16)),
                ('unit_name', models.CharField(max_length=32)),
                ('reference', models.CharField(max_length=256)),
                ('investigator_name', models.CharField(max_length=32)),
                ('phone_num', models.CharField(max_length=32)),
            ],
        ),
    ]
