# Generated by Django 3.2 on 2022-05-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseHandler', '0002_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samples',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='samples',
            name='investigator_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='samples',
            name='notes',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='samples',
            name='packaging',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='samples',
            name='phone_num',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='samples',
            name='receiving_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='samples',
            name='results',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='samples',
            name='sending_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='samples',
            name='transferred_to_lab',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='samples',
            name='unit_name',
            field=models.CharField(max_length=256),
        ),
    ]
