# Generated by Django 3.2 on 2022-01-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseHandler', '0002_auto_20211223_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('referenceType', models.CharField(max_length=100)),
                ('eventType', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=100)),
                ('InvestigatingUnit', models.CharField(max_length=100)),
                ('internalNumber', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('internalNumberyear', models.CharField(max_length=100)),
                ('referenceNumber', models.CharField(max_length=100)),
                ('eventDate', models.CharField(max_length=100)),
                ('ReceivedDate', models.CharField(max_length=100)),
                ('signDate', models.CharField(max_length=100)),
                ('eventLocation', models.CharField(max_length=100)),
                ('eventDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibits',
            fields=[
                ('exhibit_description', models.CharField(max_length=256)),
                ('case_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bag_number', models.PositiveIntegerField()),
                ('exhibits_packaging', models.CharField(max_length=256)),
                ('exhibits_mark', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Cases',
        ),
    ]
