# Generated by Django 3.2 on 2021-12-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseHandler', '0002_auto_20211223_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('referenceType', models.CharField(max_length=100)),
                ('eventType', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=100)),
                ('InvestigatingUnit', models.CharField(max_length=100)),
                ('internalNumber', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('internalNumberyear', models.CharField(max_length=100)),
                ('referenceNumber', models.CharField(max_length=100)),
                ('eventDate', models.CharField(max_length=100)),
                ('ReceivedDate', models.CharField(max_length=100)),
                ('signDate', models.CharField(max_length=100)),
                ('eventLocation', models.CharField(max_length=100)),
                ('eventDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Cases',
        ),
    ]
