# Generated by Django 3.2 on 2022-01-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseHandler', '0003_auto_20220106_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibits',
            name='bag_number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exhibits',
            name='case_id',
            field=models.IntegerField(),
        ),
    ]
