# Generated by Django 3.2 on 2022-03-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseHandler', '0003_auto_20211223_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibits',
            fields=[
                ('exhibit_description', models.CharField(max_length=256)),
                ('case_id', models.IntegerField()),
                ('bag_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('exhibits_packaging', models.CharField(max_length=256)),
                ('exhibits_mark', models.CharField(max_length=256)),
            ],
        ),
    ]
