# Generated by Django 3.2 on 2022-04-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseHandler', '0003_delete_casetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='lab_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='sender_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='sender_rank',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='sender_serial_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
