# Generated by Django 3.2 on 2022-05-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseHandler', '0003_auto_20220516_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibits',
            name='amount',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='exhibits',
            name='explosive',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='exhibits',
            name='explosive_weight',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='exhibits',
            name='handle_date',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='exhibits',
            name='received_date',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='exhibits',
            name='tnt_equivalent',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='exhibitsi',
            name='amount',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='exhibitsi',
            name='explosive',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='exhibitsi',
            name='explosive_weight',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='exhibitsi',
            name='handle_date',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='exhibitsi',
            name='received_date',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='exhibitsi',
            name='tnt_equivalent',
            field=models.CharField(max_length=128),
        ),
    ]
